Result patch
eManPrague/kaal pull request #25
Opened 2020-09-30 06:43 UTC by smidf

- ✨ `equals`, `hashCode` and `toString` implementation in anonymous *ErrorCode* class
- 🔥 The `ApiErrorResult` has been removed and `ErrorResult` is final.

2020-09-30 09:49 UTC, Del-S commented on kaal-domain/src/main/kotlin/cz/eman/kaal/domain/result/ExecutionContext.kt
> +data class ErrorResult(
Not really sure that `ErrorResult` should be final. In the CSOB app we extend it to modify code variable type and add some additional values.

2020-09-30 09:58 UTC, Del-S requested changes
Check the comments please.

2020-09-30 14:19 UTC, vsouhrada commented on kaal-domain/src/main/kotlin/cz/eman/kaal/domain/result/ExecutionContext.kt
> +data class ErrorResult(
Why is @smidf  final? This class is extend it very often. Specific process has own error result implementation based on this base class

2020-10-01 17:44 UTC, smidf commented on kaal-domain/src/main/kotlin/cz/eman/kaal/domain/result/ExecutionContext.kt
> +data class ErrorResult(
Yes, I think the `ErrorResult` extending is anti-pattern. The `Error` class / state is something, that describes the error, and the code (unique identifier), the message and the stacktrace are sufficient. If a user has the ability to extend, add, or override class attributes, he can exploit the error to pass data.

Only `ErrorCode` should be domain specific, not `ErrorResult`.

2022-02-14 12:42 UTC, PistaToth commented
Domluvili jsme se ze to zavreme. Filip ma aktualnejsi reseni.

2022-02-14 12:42 UTC, closed without merging